"""Add description to MenuItem

Revision ID: 95066bc4de74
Revises: ad1b34205581
Create Date: 2026-01-14 22:24:13.412567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95066bc4de74'
down_revision = 'ad1b34205581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'description')
    # ### end Alembic commands ###
