"""Add OrderMenuItem association object with quantities

Revision ID: 9d6b3c0dc895
Revises: 9f0decfe1638
Create Date: 2026-01-21 17:51:02.656754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6b3c0dc895'
down_revision = '9f0decfe1638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_order_menu_items_menu_item_id_menu_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_menu_items_order_id_orders')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_menuitem_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_menuitem_association',
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name='fk_order_menuitem_association_menu_item_id_menu_items'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_order_menuitem_association_order_id_orders'),
    sa.PrimaryKeyConstraint('order_id', 'menu_item_id')
    )
    op.drop_table('order_menu_items')
    # ### end Alembic commands ###
